runtime: custom
env: flex

env_variables:
    ## Put production environment variables here.
    APP_KEY: base64:Mvo23At/aI/C+Gbl418Y/S54tyZqrVsz/CIbtQxGJmE=
    APP_STORAGE: /tmp
    VIEW_COMPILED_PATH: /tmp
    SESSION_DRIVER: cookie
