steps:
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["build", "-t", "gcr.io/devopstest-250411/spindevops", "."]
timeout: "500s"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/my-project/my-image']
images: ['gcr.io/devopstest-250411/spindevops']