# steps:
#     - name: "gcr.io/cloud-builders/gcloud"
#       args: ["build", "-t", "gcr.io/devopstest-250411/spindevops", "."]
#       timeout: 500s
#     - name: "gcr.io/cloud-builders/docker"
#       args: ["push", "gcr.io/devopstest-250411/spindevops"]
# images: ["gcr.io/devopstest-250411/spindevops"]

steps:
    - name: "gcr.io/cloud-builders/gsutil"
      args:
          - cp
          - .env.example
          - .env
    - name: "docker/compose:1.23.1"
      args:
          - run
          - app
          - composer
          - install
          - --optimize-autoloader
          - --no-interaction
          - --no-ansi
          - --no-progress
          - --no-scripts
          - --prefer-dist
    - name: "docker/compose:1.23.1"
      args:
          - run
          - app
          - vendor/bin/phpunit
          - --no-coverage
    - name: "gcr.io/cloud-builders/gsutil"
      args:
          - cp
          - ${_APP_YAML_CONFIG}
          - app.yaml
    # - name: 'gcr.io/cloud-builders/gcloud'
    #   args:
    #     - app
    #     - deploy
    #     - --no-promote
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/devopstest-250411/spindevops"]
images: ["gcr.io/devopstest-250411/spindevops"]
timeout: "600s"
