version: "3.6"
services:
  app:
    build:
      context: .
    container_name: default-api-app
    ports:
      - 80:8080
    environment:
      - DOCUMENT_ROOT=/app/public
      - SKIP_LOCKDOWN_DOCUMENT_ROOT=true
      - OPCACHE_SAVE_COMMENTS=1
      - OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
      - .:/app
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: launcher.gcr.io/google/postgresql11
    container_name: default-api-pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
    volumes:
      - default-pgsql:/var/lib/postgresql/data

  redis:
    image: launcher.gcr.io/google/redis4
    container_name: default-api-redis
    volumes:
      - default-redis:/data
    ports:
      - 6379:6379

networks:
  default:
    name: default-api_default
volumes:
  default-pgsql:
    driver: local
  default-redis:
    driver: local
